# ==========================================
# WATCHBYTE CSRF PROTECTION
# ==========================================

import secrets


csrf_tokens = set()


def generate_csrf_token():
    """
    Generate and store a secure random CSRF token.
    """

    token = secrets.token_urlsafe(32)

    csrf_tokens.add(token)

    return token


def verify_csrf_token(expected_token, submitted_token):
    """
    Verify that the submitted CSRF token is valid
    and was generated by WatchByte.
    """

    if not expected_token or not submitted_token:
        return False

    if not secrets.compare_digest(
        expected_token,
        submitted_token
    ):
        return False

    return submitted_token in csrf_tokens


def remove_csrf_token(token):
    """
    Remove a CSRF token after it is no longer needed.
    """

    if token:
        csrf_tokens.discard(token)